# Numpy

In [1]:
import numpy as np
import pandas as pd


1. Create a 3x3x3 array with random values


In [2]:
x = np.random.random((3,3,3))

print (x)

[[[0.96838284 0.07997594 0.42564637]
  [0.79752608 0.19632408 0.67631177]
  [0.79341661 0.5614027  0.12612526]]

 [[0.07543146 0.72819381 0.20561997]
  [0.9606544  0.78776298 0.48337693]
  [0.25560745 0.16314145 0.19899236]]

 [[0.52136038 0.7118674  0.19669642]
  [0.58700358 0.85052448 0.21703932]
  [0.52652615 0.51232057 0.71250254]]]


_____

2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
# a. matrix using .diag()

mat_a = np.diag([1, 2, 3, 4, 5])

print(mat_a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [7]:
# b. matrix using .diag() and arange()

matrix_a = np.diag(1+np.arange(4),k=-1)

print(matrix_a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


____

3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
# a.

matrix_1 = np.zeros((8,8),dtype=int)

matrix_1[1::2,::2] = 1

matrix_1[::2,1::2] = 1

print(matrix_1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
# b.

mat2 = np.ones((4,4))
print("Checkerboard pattern:")
mat2 = np.zeros((8,8),dtype=int)
mat2[1::2,::2] = 1
mat2[::2,1::2] = 1
print(mat2)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


_______________

4. Normalize a 5x5 random matrix

In [13]:

A = np.random.random((5,5))
Amax, Amin = A.max(), A.min()
A= (A-Amin)/(Amax-Amin)
print (A)


[[0.41831163 0.66352626 0.16758368 0.68313841 0.08814198]
 [1.         0.         0.86978123 0.15886971 0.87808457]
 [0.53079692 0.60830285 0.02671995 0.95292528 0.93525366]
 [0.80950548 0.26920113 0.18193345 0.60746815 0.393624  ]
 [0.21321714 0.82722209 0.62767907 0.1664121  0.00232567]]


In [17]:
# B

B= np.random.random((4,4))
print("Original Array:")

print(B)



Bmax, Bmin = B.max(), B.min()
B = (B - Bmin)/(Bmax - Bmin)
print("After normalization:")
print(B)



Original Array:
[[0.70569053 0.71892749 0.64762284 0.36293038]
 [0.72727803 0.12836903 0.2803122  0.58922961]
 [0.66338871 0.24001429 0.89504539 0.61181986]
 [0.91448899 0.74644487 0.34461439 0.85977367]]
After normalization:
[[0.73439364 0.75123199 0.66052744 0.29837857]
 [0.76185446 0.         0.19328242 0.58624714]
 [0.68058274 0.14202065 0.97526637 0.61498354]
 [1.         0.78623603 0.27507935 0.93039825]]


_________________

5. How to find common values between two arrays?

In [18]:
# a. Using .array() and .intersection1d()

array1 = np.array([10, 20, 40, 60, 80, 70, 100, 55, 35, 85,])

print("Array1: ",array1)

array2 = [10, 100, 80, 70, 40]

print("Array2: ",array2)

print("Common values between two arrays:")


print(np.intersect1d(array1, array2))

Array1:  [ 10  20  40  60  80  70 100  55  35  85]
Array2:  [10, 100, 80, 70, 40]
Common values between two arrays:
[ 10  40  70  80 100]


In [75]:
# b. using .random and .randint()

arr1 = np.random.randint(0,10,10)

arr2 = np.random.randint(0,10,10)

print(np.intersect1d(arr1,arr2))



[0 1 4 5 6 7]


__________

6. How to get the dates of yesterday, today and tomorrow?

##### Need to import Datetime Module to find dates

* datetime - module helps to find the present day by using the now() or today() method.
* timedelta - class from datetime module helps to find the previous day date and next day date.

###### Syntax to find a present-day date:

datetime.now()     # Returns: A datetime object containing the current local date and time.

###### Syntax to find a previous-day and next-day date:

previous-day = datetime.now()-timedelta(1)

next-day = datetime.now()+timedelta(1)

In [28]:

from datetime import datetime, timedelta

today = datetime.today()      # presentday = datetime.now() can also be used

yesterday = today - timedelta(1) 
  
tomorrow = today + timedelta(1) 

today = input("Enter today's date : ")     # input from user in date format : dd-mm-yyyy

print(today)
print(tomorrow)
print(yesterday)



Enter today's date : 25-07-2020
25-07-2020
2020-07-26 20:27:32.491239
2020-07-24 20:27:32.491239


In [25]:
# b.

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')


print(yesterday)
print(today)
print(tomorrow)

2020-07-24
2020-07-25
2020-07-26


_____

In [ ]:
7. Consider two random array A and B, check if they are equal

In [29]:
x = np.random.randint(0,2,6)
print("First array:")

print(x)

y = np.random.randint(0,2,6)
print("Second array:")

print(y)

print("Test above two arrays are equal or not!")

array_equal = np.allclose(x, y)

print(array_equal)

First array:
[0 1 1 1 1 1]
Second array:
[0 0 1 0 1 1]
Test above two arrays are equal or not!
False


In [32]:
A = np.random.randint(0,2,10)

print(A)

B = np.random.randint(0,2,10)

print(B)

equal = np.allclose(A,B)

print(equal)

[1 0 0 1 0 1 1 0 1 1]
[0 1 1 1 0 0 0 1 1 0]
False


____________

8.Create random vector of size 10 and replace the maximum value by 0

In [33]:
A = np.random.random(10)

A[A.argmax()] = 0

print(A)


[0.         0.13097838 0.04398211 0.449949   0.62193993 0.45597204
 0.51351353 0.80370599 0.21869386 0.49898541]


____

9. How to print all the values of an array?

In [40]:
# a.
A = np.zeros((8,8))
A

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
# b.
np.set_printoptions()

A = np.zeros((10,10))

print(A)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


________

10. Subtract the mean of each row of a matrix

In [51]:
# a. 
print("Original matrix:\n")

A = np.random.rand(8, 6)

print(A)

print("\nSubtract the mean of each row of the said matrix:\n")

B = A - A.mean(axis=1, keepdims=True)

print(B)

Original matrix:

[[0.64927496 0.47590752 0.26576983 0.21672684 0.6087602  0.67833388]
 [0.48172724 0.12789971 0.82469947 0.9805648  0.50940657 0.59396581]
 [0.58673885 0.30764043 0.82125811 0.52112625 0.63889434 0.38799733]
 [0.41806758 0.12367763 0.59976599 0.90686829 0.26729226 0.08418663]
 [0.3721344  0.4872919  0.62468261 0.17969206 0.01508945 0.5399036 ]
 [0.55468635 0.9709677  0.71794396 0.37361583 0.46950525 0.03673519]
 [0.76167731 0.93402873 0.31192243 0.49930438 0.05181365 0.12399443]
 [0.41037032 0.44704066 0.04509208 0.04971343 0.93452948 0.88655428]]

Subtract the mean of each row of the said matrix:

[[ 0.16681275 -0.00655469 -0.21669237 -0.26573536  0.12629799  0.19587168]
 [-0.10465002 -0.45847756  0.23832221  0.39418753 -0.0769707   0.00758854]
 [ 0.0427963  -0.23630212  0.27731556 -0.0228163   0.09495179 -0.15594522]
 [ 0.01809119 -0.27629877  0.19978959  0.50689189 -0.13268414 -0.31578976]
 [ 0.00233539  0.1174929   0.25488361 -0.19010694 -0.35470956  0.1701046 ]
 [

In [54]:
# b.
A = np.random.rand(3, 6)   
print(A)

B = A - A.mean(axis=1, keepdims=True)

print(B)

[[0.14073728 0.45161068 0.94224095 0.49935104 0.27451894 0.82338728]
 [0.25872356 0.97861175 0.58304454 0.08542022 0.01605868 0.97160708]
 [0.20114708 0.99458147 0.27835006 0.58556831 0.51767618 0.58475123]]
[[-0.38123708 -0.07036368  0.42026658 -0.02262332 -0.24745542  0.30141292]
 [-0.22352074  0.49636744  0.10080023 -0.39682408 -0.46618562  0.48936277]
 [-0.32586531  0.46756908 -0.24866232  0.05855592 -0.0093362   0.05773884]]


_________

11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [55]:
# a.

Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

[3. 2. 4. 4. 1. 2. 2. 3. 6. 3.]


In [57]:
# b.

A = np.ones(10)

B = np.random.randint(0,len(A),20)

np.add.at(A, B, 1)

print(A)

[2. 5. 6. 2. 2. 3. 3. 3. 2. 2.]


_________


12. How to get the diagonal of a dot product?


In [60]:
# a.

A = np.random.uniform(0,1,(4,4))

B = np.random.uniform(0,1,(4,4))

np.diag(np.dot(A, B))


array([0.96835432, 0.7083237 , 2.31853273, 0.68591791])

In [61]:
# b.

A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

np.sum(A * B.T, axis=1)



array([1.21424552, 2.84723985, 1.15293753, 0.60741609, 0.90901348])

In [ ]:
13. How to find the most frequent value in an array?

In [62]:

a = np.random.randint(0, 10, 40)

print("Original array:")

print(a)

print("Most frequent value in the above array:")

print(np.bincount(a).argmax())


Original array:
[6 4 6 0 6 9 2 4 1 5 4 8 0 5 0 2 0 0 0 7 4 2 9 1 5 6 8 9 1 4 3 4 6 7 9 5 8
 2 6 2]
Most frequent value in the above array:
0


_____________

14. How to get the n largest values of an array

In [68]:
# a. Using .argsort()
a = np.arange(15)

print("Original array:")

print(a)

np.random.shuffle(a)

n = 1


print("Largest values of an array :")

print (a[np.argsort(a)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Largest values of an array :
[14]


In [69]:
# b. Using .argpartition()

a = np.arange(10)

print("Original array:")

print(a)

np.random.shuffle(a)

n = 1

print("Largest values of an array :")

print (a[np.argpartition(-a,n)[:n]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest values of an array :
[9]


_____________


15. How to create a record array from a regular array?


In [70]:
# a.

a1=np.array([1,2,3,4])
a2=np.array(['Apple','Mac','Microsoft','Linux'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])






(1, 'Apple', 12.2)
(2, 'Mac', 15.)
(3, 'Microsoft', 20.)


In [74]:
# b.
import numpy as np
arra1 = np.array([("Rohit S", 88.5, 90),
                 ("Ajay M", 87, 99),
             ("Monisha S", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Rohit S' '88.5' '90']
 ['Ajay M' '87' '99']
 ['Monisha S' '85.5' '91']]

Record array;
[(b'Rohit S', 88.5, 90) (b'Ajay M', 87. , 99) (b'Monisha S', 85.5, 91)]


____________